-- Demo hotels with their phone numbers, breakfasts and services.
-- Rooms are generated by db.sample.V1_2__Sample_rooms.

INSERT INTO `hotel` (`HotelID`, `Street`, `City`, `State`, `ZIP`, `Country`) VALUES
  (1, '250 Park Ave', 'New York', 'NY', '10177', 'United States'),
  (2, '1 Market St', 'San Francisco', 'CA', '94105', 'United States'),
  (3, '400 Ocean Dr', 'Miami Beach', 'FL', '33139', 'United States'),
  (4, '120 Front St W', 'Toronto', 'ON', 'M5J 2L7', 'Canada');

INSERT INTO `hotelphones` (`Phone_no`, `HotelID`) VALUES
  ('212-555-0100', 1),
  ('212-555-0101', 1),
  ('415-555-0120', 2),
  ('305-555-0140', 3),
  ('416-555-0160', 4);

INSERT INTO `breakfast` (`bType`, `HotelID`, `Description`, `bPrice`) VALUES
  ('Continental', 1, 'Pastries, fruit, yogurt and coffee', 18.00),
  ('American', 1, 'Eggs, bacon, pancakes and coffee', 26.00),
  ('Continental', 2, 'Sourdough, fruit, granola and coffee', 16.00),
  ('Vegan', 2, 'Tofu scramble, avocado toast and smoothies', 22.00),
  ('Continental', 3, 'Tropical fruit, pastries and Cuban coffee', 15.00),
  ('American', 3, 'Eggs, bacon, waffles and juice', 24.00),
  ('Continental', 4, 'Bagels, fruit, yogurt and coffee', 17.00),
  ('American', 4, 'Eggs, peameal bacon, pancakes and maple syrup', 25.00);

INSERT INTO `service` (`sType`, `HotelID`, `sCost`) VALUES
  ('Airport shuttle', 1, 45.00),
  ('Laundry', 1, 20.00),
  ('Spa', 1, 120.00),
  ('Airport shuttle', 2, 40.00),
  ('Bike rental', 2, 25.00),
  ('Spa', 3, 110.00),
  ('Cabana', 3, 80.00),
  ('Airport shuttle', 4, 35.00),
  ('Laundry', 4, 18.00);
